import Head from "next/head";
import {
  Button,
  Spinner,
  Table,
  TableContainer,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
  Flex,
  Heading,
} from "@chakra-ui/react";
import { Container, TitlePage, Title, ButtonWrapper, Main } from "./style";
import ModalCreateLaboratory from "@/components/Modals/LaboratoryCreation";
import { LaboratoryManagementModal } from "@/components/Modals/LaboratoryManagement";
import { IViewLaboratory } from "./types";

export const ViewLaboratory = ({
  handleOpenModalCreate,
  isLoading,
  laboratories,
  handleLaboratoryClick,
  isModalCreateOpen,
  handleCloseModalCreate,
  selectedLaboratoryId,
  handleCloseLaboratoryDetails,
}: IViewLaboratory) => {
  return (
    <>
      <Head>
        <title>Laboratórios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Main>
        <Container>
          <TitlePage>
            <Heading as="h1" size="lg" textAlign="center" mb="6">
              Lista de Laboratórios
            </Heading>
            <ButtonWrapper>
              <Button
                bg="#006a12"
                _hover={{ bg: "green.500" }}
                color="white"
                onClick={handleOpenModalCreate}
              >
                + <span>Laboratório</span>
              </Button>
            </ButtonWrapper>
          </TitlePage>

          <TableContainer>
            {isLoading ? (
              <Flex justify="center" align="center" height="600px">
                <Spinner
                  thickness="10px"
                  speed="0.65s"
                  emptyColor="gray.200"
                  width={150}
                  height={150}
                  color="green.500"
                />
              </Flex>
            ) : (
              <Table variant="simple" colorScheme="green">
                <Thead>
                  <Tr>
                    <Th>Nome</Th>
                    <Th>Quantidade de máquinas</Th>
                    <Th>Softwares</Th>
                    <Th>Observações</Th>
                  </Tr>
                </Thead>
                <Tbody>
                  {laboratories?.map((laboratory) => (
                    <Tr
                      key={laboratory.id}
                      onClick={() => handleLaboratoryClick(laboratory.id)}
                      style={{ cursor: "pointer" }}
                      _hover={{ bg: "green.100", boxShadow: "md" }}
                    >
                      <Td>{laboratory.name}</Td>
                      <Td>{laboratory.machineQuantity}</Td>
                      <Td>{laboratory.softwares}</Td>
                      <Td>{laboratory.observations}</Td>
                    </Tr>
                  ))}
                </Tbody>
              </Table>
            )}
          </TableContainer>
          <ModalCreateLaboratory
            isOpen={isModalCreateOpen}
            onClose={handleCloseModalCreate}
          />
          <LaboratoryManagementModal
            laboratoryId={selectedLaboratoryId}
            onClose={handleCloseLaboratoryDetails}
          />
        </Container>
      </Main>
    </>
  );
};
