import Head from "next/head";
import {
  Button,
  Spinner,
  Table,
  TableContainer,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
  Flex,
  Heading,
} from "@chakra-ui/react";
import { Container, TitlePage, Title, ButtonWrapper, Main } from "./style";
import ModalCreateDiscipline from "@/components/Modals/DisciplineCreation";
import { DisciplineManagementModal } from "@/components/Modals/DisciplineManagement";
import { IViewDicipline } from "./types";

export const ViewDiscipline = ({
  handleOpenModalCreate,
  loading,
  subjects,
  handleDisciplineClick,
  isModalCreateOpen,
  handleCloseModalCreate,
  selectedDisciplineId,
  handleCloseDisciplineDetails,
  fetchSubjects,
}: IViewDicipline) => {
  return (
    <>
      <Head>
        <title>Disciplinas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Main>
        <Container>
          <TitlePage>
            <Heading as="h1" size="lg" textAlign="center" mb="6">
              Lista de Disciplinas
            </Heading>
            <ButtonWrapper>
              <Button
                bg="#006a12"
                _hover={{ bg: "green.500" }}
                color="white"
                onClick={handleOpenModalCreate}
              >
                + <span>Disciplina</span>
              </Button>
            </ButtonWrapper>
          </TitlePage>

          <TableContainer>
            {loading ? (
              <Flex justify="center" align="center" height="600px">
                <Spinner
                  thickness="10px"
                  speed="0.65s"
                  emptyColor="gray.200"
                  width={150}
                  height={150}
                  color="green.500"
                />
              </Flex>
            ) : (
              <Table variant="simple" colorScheme="green">
                <Thead>
                  <Tr>
                    <Th>Nome</Th>
                  </Tr>
                </Thead>
                <Tbody>
                  {subjects.map((subject) => (
                    <Tr
                      key={subject.id}
                      onClick={() => handleDisciplineClick(subject.id)}
                      style={{ cursor: "pointer" }}
                      _hover={{ bg: "green.100", boxShadow: "md" }}
                    >
                      <Td>{subject.name}</Td>
                    </Tr>
                  ))}
                </Tbody>
              </Table>
            )}
          </TableContainer>
          <ModalCreateDiscipline
            isOpen={isModalCreateOpen}
            onClose={handleCloseModalCreate}
          />
          <DisciplineManagementModal
            disciplineId={selectedDisciplineId}
            onClose={handleCloseDisciplineDetails}
            onDisciplineUpdated={fetchSubjects}
          />
        </Container>
      </Main>
    </>
  );
};
