import Head from "next/head";
import { FormControl } from "@chakra-ui/react";
import {
  Container,
  LoginContainer,
  ButtonContainer,
  LoginTitle,
  LoginForm,
  EmailInput,
  PasswordInputContainer,
  PasswordInput,
  EyeIconContainer,
  UnBlockedEyeIcon,
  BlockedEyeIcon,
  LoginOptionText,
  GoogleIcon,
  LoginButton,
  GoogleLoginButton,
  GoogleLoginText,
} from "./styles";
import { IViewLogin } from "./types";
import ReCAPTCHA from "react-google-recaptcha";

export const ViewLogin = ({
  setPassword,
  password,
  setEmail,
  email,
  handleSubmit,
  handleChangePasswordInputType,
  passwordInputType,
  handleVerifyRecaptcha,
  isButtonDisabled,
  handleOauth,
}: IViewLogin) => {
  return (
    <>
      <Head>
        <title>Laboratório B208</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        {/* <ImageContainer>
          
        </ImageContainer> */}
        <LoginContainer>
          <LoginTitle>Login</LoginTitle>
          <LoginForm onSubmit={handleSubmit}>
            <FormControl>
              <EmailInput
                type="email"
                placeholder="Email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <PasswordInputContainer>
                <PasswordInput
                  type={passwordInputType}
                  placeholder="Senha"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                />
                <EyeIconContainer onClick={handleChangePasswordInputType}>
                  {passwordInputType === "password" ? (
                    <BlockedEyeIcon />
                  ) : (
                    <UnBlockedEyeIcon />
                  )}
                </EyeIconContainer>
              </PasswordInputContainer>

              <ReCAPTCHA
                sitekey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY as string}
                data-type="image"
                onChange={handleVerifyRecaptcha}
              />

              <ButtonContainer>
                <LoginButton type="submit" isDisabled={!isButtonDisabled}>
                  Acessar
                </LoginButton>

                <LoginOptionText>ou</LoginOptionText>

                <GoogleLoginButton onClick={handleOauth}>
                  <GoogleIcon />{" "}
                  <GoogleLoginText>Logar com conta Google</GoogleLoginText>
                </GoogleLoginButton>
              </ButtonContainer>
            </FormControl>
          </LoginForm>
        </LoginContainer>
      </Container>
    </>
  );
};
