import Head from "next/head";
import styles from "@/styles/Home.module.css";
import {
  Button,
  Spinner,
  Table,
  TableContainer,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
  Flex,
  Heading,
} from "@chakra-ui/react";
import { Container, TitlePage, ButtonWrapper } from "./style";
import TeacherModal from "@/components/Modals/ProfessorManagement";
import ModalCreateTeacher from "@/components/Modals/ProfessorCreation";
import { IViewTeacher } from "./types";

export const ViewProfessorManagement = ({
  handleOpenCreateModal,
  isLoading,
  professors,
  handleTeacherClick,
  isModalOpen,
  selectedTeacherId,
  handleCloseModal,
  isCreateModalOpen,
  handleCloseCreateModal,
}: IViewTeacher) => {
  return (
    <>
      <Head>
        <title>Professores</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main}`}>
        <Container>
          <TitlePage>
            <Heading as="h1" size="lg" textAlign="center" mb="6">
              Lista de professores
            </Heading>
            <ButtonWrapper>
              <Button
                bg="#006a12"
                _hover={{ bg: "green.500" }}
                color="white"
                onClick={handleOpenCreateModal}
              >
                + <span>Professor</span>
              </Button>
            </ButtonWrapper>
          </TitlePage>

          <TableContainer>
            {isLoading ? (
              <Flex justify="center" align="center" height="600px">
                <Spinner
                  thickness="10px"
                  speed="0.65s"
                  emptyColor="gray.200"
                  width={150}
                  height={150}
                  color="green.500"
                />
              </Flex>
            ) : (
              <Table variant="simple" colorScheme="green">
                <Thead>
                  <Tr>
                    <Th>Nome</Th>
                    <Th>E-mail</Th>
                    <Th>ID do Funcionário</Th>
                  </Tr>
                </Thead>
                <Tbody>
                  {professors?.map((professor) => (
                    <Tr
                      key={professor?.id}
                      onClick={() => handleTeacherClick(professor?.id)}
                      style={{ cursor: "pointer" }}
                      _hover={{ bg: "green.100", boxShadow: "md" }}
                    >
                      <Td>{professor?.name}</Td>
                      <Td>{professor?.email}</Td>
                      <Td>{professor?.employee_id}</Td>
                    </Tr>
                  ))}
                </Tbody>
              </Table>
            )}
          </TableContainer>

          <TeacherModal
            isOpen={isModalOpen}
            teacherId={selectedTeacherId}
            onClose={handleCloseModal}
          />

          <ModalCreateTeacher
            isOpen={isCreateModalOpen}
            onClose={handleCloseCreateModal}
          />
        </Container>
      </main>
    </>
  );
};
